DUKTAPE_SOURCES = src/duktape.c

CC	= gcc
CCOPTS	= -Os -pedantic -std=c99 -Wall -fstrict-aliasing -fomit-frame-pointer
CCOPTS += -I./src  # for combined sources
CCLIBS	= -lm
CCOPTS += -UK_USE_FATAL_HANDLER

hello:	$(DUKTAPE_SOURCES) examples/hello/hello.c
	$(CC) -o $@ $(DEFINES) $(CCOPTS) $(DUKTAPE_SOURCES) examples/hello/hello.c $(CCLIBS)
